// Generator that converts a schema yaml file to schema and type definitions golang files.
// Usage of gen:
// 	gen schema_input.yaml

//go:build ignore

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"io/ioutil"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

type Property struct {
	Type struct {
		TypeID string `yaml:"type_id"`
		Id     string `yaml:"id"`
	} `yaml:"type"`
	Display struct {
		Name        string `yaml:"name"`
		Description string `yaml:"description"`
	} `yaml:"display"`
	Required bool `yaml:"required"`
}

var Schema struct {
	Steps struct {
		Create struct {
			Id    string `yaml:"id"`
			Input struct {
				Objects map[string]struct {
					Id         string               `yaml:"id"`
					Properties map[string]*Property `yaml:"properties"`
				} `yaml:"objects"`
			} `yaml:"input"`
		} `yaml:"create"`
	} `yaml:"steps"`
}

func main() {
	Env()

	inputFile, err := ioutil.ReadFile(os.Args[1])
	check(err)

	err = yaml.Unmarshal(inputFile, &Schema)
	check(err)

	bufTypeDef := new(bytes.Buffer) // Accumulated output for type def
	bwt := bufio.NewWriter(bufTypeDef)
	fmt.Fprintf(bwt, "// Code generated by \"gen %s\"; DO NOT EDIT.\n", strings.Join(os.Args[1:], " "))
	fmt.Fprintf(bwt, typeDefImports)
	for o, ov := range Schema.Steps.Create.Input.Objects {
		if o == "ObjectMeta" { // Object ObjectMeta should be ignored
			continue
		}
		fmt.Fprintf(bwt, "\ntype %v struct {\n", strings.Title(o))
		for p, pv := range ov.Properties {
			var varType string
			if pv.Type.TypeID == "ref" {
				varType = pv.Type.Id
			} else {
				varType = pv.Type.TypeID
			}
			fmt.Fprintf(bwt, "\t%v %v "+"`"+`json:"%v"`+"`"+"\n", strings.Title(p), parseType(varType), p)
		}
		fmt.Fprintf(bwt, "}\n")
	}

	err = bwt.Flush()
	check(err)

	srcTypeDef, err := format.Source(bufTypeDef.Bytes())
	check(err)

	err = os.WriteFile("typedef_output.go", srcTypeDef, 0644)
	check(err)

	fmt.Println("\nOutput written to file: typedef_output.go")
}

func check(e error) {
	if e != nil {
		panic(e)
	}
}

func Env() {
	fmt.Printf("Running %s go on %s\n", os.Args[0], os.Getenv("GOFILE"))
	cwd, err := os.Getwd()
	check(err)
	fmt.Printf("\tcwd = %s\n", cwd)
	fmt.Printf("\tos.Args = %#v\n", os.Args)
	for _, ev := range []string{"GOFILE", "GOLINE", "GOPACKAGE"} {
		fmt.Println("\t", ev, "=", os.Getenv(ev))
	}
}

func parseType(schemaType string) string {
	switch schemaType {
	case "integer":
		return "int64"
	case "float":
		return "float64"
	default:
		return schemaType
	}
}

const typeDefImports = `package arcaflow_plugin_service

import (
    v1 "k8s.io/api/core/v1"
    metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)
`
